CREATE TABLE [dbo].[PRODUCTO]
(
[IDPROD] [int] NOT NULL IDENTITY(1, 1),
[NOMPROD] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DESCPROD] [varchar] (70) COLLATE Modern_Spanish_CI_AS NOT NULL,
[MARPROD] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PREPROD] [decimal] (8, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_pk] PRIMARY KEY CLUSTERED ([IDPROD]) ON [PRIMARY]
GO
