CREATE TABLE [dbo].[VENTA]
(
[CODVENT] [char] (5) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDCLI] [int] NOT NULL,
[IDVEN] [int] NOT NULL,
[CODVENTDET] [char] (5) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TIPPAGVEN] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_pk] PRIMARY KEY CLUSTERED ([CODVENT]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_CLIENTE] FOREIGN KEY ([IDCLI]) REFERENCES [dbo].[CLIENTE] ([IDCLI])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_VENDEDOR] FOREIGN KEY ([IDVEN]) REFERENCES [dbo].[VENDEDOR] ([IDVEN])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_VENTA_DETALLE] FOREIGN KEY ([CODVENTDET]) REFERENCES [dbo].[VENTA_DETALLE] ([CODVENTDET])
GO
