CREATE TABLE [dbo].[VENDEDOR]
(
[IDVEN] [int] NOT NULL IDENTITY(1, 1),
[NOMVEN] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEVEN] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DNIVEN] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CELVEN] [char] (9) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRVEN] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTVEN] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENDEDOR] ADD CONSTRAINT [VENDEDOR_pk] PRIMARY KEY CLUSTERED ([IDVEN]) ON [PRIMARY]
GO
