CREATE TABLE [dbo].[VENTA_DETALLE]
(
[CODVENTDET] [char] (5) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CANTPROD] [int] NOT NULL,
[FECVENTDET] [date] NOT NULL,
[IDPROD] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_pk] PRIMARY KEY CLUSTERED ([CODVENTDET]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_PRODUCTO] FOREIGN KEY ([IDPROD]) REFERENCES [dbo].[PRODUCTO] ([IDPROD])
GO
